#!/usr/bin/env julia

using Coverage
using Dates
using JSON
using Pkg
using SHA
using TOML
using YAML

include(joinpath(@__DIR__, "sanitize.jl"))

const ROOT = normpath(joinpath(@__DIR__, ".."))
const OUTPUT = joinpath(@__DIR__, "output")
const CARDS = joinpath(@__DIR__, "cards")
const PACKAGES = [
    "BookKit",
    "CondaR",
    "ConfigKit",
    "InjecKit",
    "QSPKitCore",
    "QSPKitIO",
    "QSPReports",
    "ShowKit",
    "SimKit",
    "SpecKit",
    "StoreKit",
    "TargKit",
]
const AGGREGATE_NAME = "QSPKit"
const AGGREGATE_VERSION = "0.1.0-alpha.1"
const REQUIRED_SCORE_CATEGORIES =
    ("testing", "documentation", "maintenance", "transparency")
const MANIFEST_BINDING_POLICY = "run-resolved-untracked"
const EXPECTED_ARCHIVE_DIGEST_CACHE = Dict{Tuple{String, String, String}, String}()

json_file(path, value) = open(path, "w") do io
    JSON.print(io, value, 2)
    println(io)
end

package_project(pkg) = TOML.parsefile(joinpath(ROOT, pkg, "Project.toml"))
package_version(pkg) = string(package_project(pkg)["version"])
result_name(pkg) = "$(pkg)_$(package_version(pkg))"
result_dir(pkg) = joinpath(OUTPUT, result_name(pkg))
result_prefix(pkg) = joinpath(result_dir(pkg), result_name(pkg))
aggregate_result_name() = "$(AGGREGATE_NAME)_$(AGGREGATE_VERSION)"
aggregate_result_dir() = joinpath(OUTPUT, aggregate_result_name())
aggregate_prefix() = joinpath(aggregate_result_dir(), aggregate_result_name())
matrix_path(pkg) = joinpath(@__DIR__, "matrix-$(pkg).yaml")

function normalize_export(token)
    token = strip(token)
    isempty(token) && return nothing
    return token
end

"""
Return the supported exported API inventory for a package.

Most packages use explicit `export` statements in their main module. Packages
whose exports are generated by metaprogramming may provide a reviewed
`validation/exports-<package>.txt` inventory so linting stays deterministic and
does not initialize optional runtimes merely to inspect a module.
"""
function exported_symbols(pkg)
    inventory_path = joinpath(@__DIR__, "exports-$(pkg).txt")
    if isfile(inventory_path)
        inventory = String[]
        for raw_line in eachline(inventory_path)
            token = strip(first(split(raw_line, '#'; limit=2)))
            isempty(token) || push!(inventory, token)
        end
        isempty(inventory) && error("$pkg exported API inventory is empty")
        length(inventory) == length(unique(inventory)) ||
            error("$pkg exported API inventory contains duplicates")
        return inventory
    end

    path = joinpath(ROOT, pkg, "src", "$(pkg).jl")
    exports = String[]
    continuing = false
    for raw_line in eachline(path)
        code = strip(first(split(raw_line, '#'; limit=2)))
        if startswith(code, "export ")
            payload = strip(code[8:end])
            continuing = endswith(payload, ',')
        elseif continuing
            isempty(code) && continue
            payload = code
            continuing = endswith(payload, ',')
        else
            continue
        end
        for token in split(payload, ',')
            normalized = normalize_export(token)
            normalized === nothing || push!(exports, normalized)
        end
    end
    return unique(exports)
end

function safe_package_path(pkg, relative_path, kind)
    relative_path isa AbstractString || error("$pkg $kind path is not a string")
    isabspath(relative_path) && error("$pkg $kind path must be package-relative: $relative_path")
    normalized = normpath(relative_path)
    (normalized == ".." || startswith(normalized, ".." * Base.Filesystem.path_separator)) &&
        error("$pkg $kind path escapes the package: $relative_path")
    candidate = joinpath(ROOT, pkg, normalized)
    isfile(candidate) || error("$pkg $kind path does not exist: $relative_path")
    return normalized
end

function read_matrix(pkg)
    path = matrix_path(pkg)
    isfile(path) || error("missing traceability matrix: $(relpath(path, ROOT))")
    rows = YAML.load_file(path)
    rows isa AbstractVector || error("$pkg matrix must contain a YAML list")
    isempty(rows) && error("$pkg matrix is empty")
    return rows
end

function git_blob_bytes(commit, repository_path; root=ROOT)
    spec = "$(commit):$(replace(repository_path, '\\' => '/'))"
    return read(Cmd(["git", "-C", root, "show", spec]))
end

function validate_package_matrix_copy(path, pkg; release=true, commit=nothing, root=ROOT)
    expected = if release
        commit === nothing && error("release matrix validation requires a commit")
        git_blob_bytes(commit, "validation/matrix-$pkg.yaml"; root)
    else
        read(matrix_path(pkg))
    end
    read(path) == expected || error(
        "$pkg copied matrix does not exactly match " *
        (release ? "the matrix at $commit" : "the current package matrix"))
    return true
end

"""Return literal `include("...")` arguments from executable Julia syntax."""
function literal_includes(source::AbstractString; filename="none")
    syntax = Meta.parseall(source; filename)
    includes = String[]

    function visit(node)
        node isa Expr || return
        node.head in (:quote, :inert) && return
        if node.head == :call && length(node.args) == 2 &&
           node.args[1] === :include && node.args[2] isa String
            push!(includes, node.args[2])
        end
        foreach(visit, node.args)
    end

    visit(syntax)
    return includes
end

"""Return the package-relative files reached by literal `include("...")` calls."""
function executed_test_files(pkg)
    test_root = joinpath(ROOT, pkg, "test")
    entrypoint = joinpath(test_root, "runtests.jl")
    isfile(entrypoint) || error("$pkg has no canonical test/runtests.jl")
    visited = Set{String}()

    function visit(path)
        absolute = normpath(path)
        relative = relpath(absolute, joinpath(ROOT, pkg))
        relative in visited && return
        isfile(absolute) || error("$pkg test suite includes a missing file: $relative")
        push!(visited, relative)
        source = read(absolute, String)
        for included in literal_includes(source; filename=absolute)
            visit(joinpath(dirname(absolute), included))
        end
    end

    visit(entrypoint)
    return visited
end

"""Validate matrix schema, file paths, uniqueness, and complete exported API coverage."""
function validate_matrix(pkg)
    rows = read_matrix(pkg)
    executed_tests = executed_test_files(pkg)
    entrypoints = String[]
    for (index, row) in pairs(rows)
        row isa AbstractDict || error("$pkg matrix row $index is not a mapping")
        for key in ("entrypoint", "code", "doc", "tests")
            haskey(row, key) || error("$pkg matrix row $index is missing `$key`")
        end
        entrypoint = string(row["entrypoint"])
        isempty(strip(entrypoint)) && error("$pkg matrix row $index has an empty entrypoint")
        push!(entrypoints, entrypoint)

        code = safe_package_path(pkg, row["code"], "code")
        startswith(code, "src" * Base.Filesystem.path_separator) ||
            error("$pkg code evidence must be under src/: $code")
        occursin(entrypoint, read(joinpath(ROOT, pkg, code), String)) ||
            error("$pkg code evidence does not name `$entrypoint`: $code")

        doc = safe_package_path(pkg, row["doc"], "documentation")
        (startswith(doc, "docs" * Base.Filesystem.path_separator) || doc == "README.md") ||
            error("$pkg documentation evidence must be README.md or under docs/: $doc")
        occursin(entrypoint, read(joinpath(ROOT, pkg, doc), String)) ||
            error("$pkg documentation evidence does not name `$entrypoint`: $doc")

        tests = row["tests"]
        tests isa AbstractVector || error("$pkg matrix row $index `tests` must be a list")
        isempty(tests) && error("$pkg matrix row $index has no test evidence")
        for test_path in tests
            test = safe_package_path(pkg, test_path, "test")
            startswith(test, "test" * Base.Filesystem.path_separator) ||
                error("$pkg test evidence must be under test/: $test")
            test in executed_tests ||
                error("$pkg test evidence is not reached from test/runtests.jl: $test")
        end
    end

    length(entrypoints) == length(unique(entrypoints)) ||
        error("$pkg matrix contains duplicate entrypoints")
    expected = Set(exported_symbols(pkg))
    actual = Set(entrypoints)
    missing = sort!(collect(setdiff(expected, actual)))
    extra = sort!(collect(setdiff(actual, expected)))
    isempty(missing) || error("$pkg matrix is missing exported APIs: $(join(missing, ", "))")
    isempty(extra) || error("$pkg matrix contains non-exported APIs: $(join(extra, ", "))")
    return rows
end

function validate_all_matrices()
    for pkg in PACKAGES
        rows = validate_matrix(pkg)
        println("validated $pkg matrix: $(length(rows)) exported entrypoints")
    end
    return true
end

function clean_coverage(pkg; root=ROOT)
    package_root = joinpath(root, pkg)
    isdir(package_root) || return
    for (dir, _, files) in walkdir(package_root)
        for file in files
            endswith(file, ".cov") && rm(joinpath(dir, file); force=true)
        end
    end
end

generated_environment_filename(name) =
    name in ("Manifest.toml", "LocalPreferences.toml", "JuliaLocalPreferences.toml") ||
    occursin(r"^Manifest-v\d+\.\d+\.toml$", name)

function remove_generated_path(path)
    (ispath(path) || islink(path)) || return 0
    if islink(path)
        rm(path; force=true)
    else
        rm(path; force=true, recursive=isdir(path))
    end
    return 1
end

function clean_environment_artifacts(; root=ROOT, packages=PACKAGES)
    environment_dirs = [root, joinpath(root, "validation")]
    for pkg in packages
        package_root = joinpath(root, pkg)
        append!(environment_dirs, [
            package_root,
            joinpath(package_root, "test"),
            joinpath(package_root, "docs"),
        ])
    end

    removed = 0
    for directory in unique(environment_dirs)
        isdir(directory) || continue
        for name in readdir(directory)
            generated_environment_filename(name) || continue
            removed += remove_generated_path(joinpath(directory, name))
        end
        removed += remove_generated_path(joinpath(directory, ".CondaPkg"))
        removed += remove_generated_path(joinpath(directory, "Rplots.pdf"))
    end
    for pkg in packages
        docs = joinpath(root, pkg, "docs")
        removed += remove_generated_path(joinpath(docs, "build"))
        removed += remove_generated_path(joinpath(docs, "site"))
    end
    return removed
end

function sanitize_transcript(text::AbstractString;
                             root::AbstractString=ROOT,
                             home::AbstractString=homedir(),
                             bug_reports_url::AbstractString=strip(get(ENV, "QSPKIT_BUG_REPORTS_URL", "")))
    sanitized = String(text)
    replacements = Pair{String, String}[]
    function add_replacements(private_value, label)
        isempty(private_value) && return
        value = String(private_value)
        for variant in unique([value, replace(value, '\\' => "\\\\"),
                               replace(value, '/' => "\\/")])
            push!(replacements, variant => label)
        end
    end
    add_replacements(root, "<QSPKIT_ROOT>")
    home == "/" || add_replacements(home, "<HOME>")
    add_replacements(bug_reports_url, "<BUG_REPORTS_URL>")
    sort!(replacements; by=pair -> -length(first(pair)))
    for (private_value, label) in replacements
        sanitized = replace(sanitized, private_value => label)
    end
    for regex in SANITIZATION_HOME_REGEXES
        sanitized = replace(sanitized, regex => "<PRIVATE_PATH>")
    end
    return sanitized
end

function validate_public_text_payload(text::AbstractString, label)
    sanitize_transcript(text) == text ||
        error("$label contains an unsanitized local path or endpoint")
    findings = scan_text(text, label)
    isempty(findings) || throw(sanitization_error("$label privacy scan", findings))
    return true
end

function publish_sanitized_transcript!(raw_path, destination)
    sanitized = sanitize_transcript(read(raw_path, String))
    validate_public_text_payload(sanitized, basename(destination))
    mkpath(dirname(destination))
    temporary, io = mktemp(dirname(destination))
    try
        write(io, sanitized)
        close(io)
        mv(temporary, destination; force=true)
    catch
        isopen(io) && close(io)
        ispath(temporary) && rm(temporary; force=true)
        rethrow()
    end
    return destination
end

function capture_sanitized_transcripts(runner, stdout_path, stderr_path)
    return mktempdir() do capture_dir
        raw_stdout = joinpath(capture_dir, "stdout")
        raw_stderr = joinpath(capture_dir, "stderr")
        result = open(raw_stdout, "w") do stdout_io
            open(raw_stderr, "w") do stderr_io
                runner(stdout_io, stderr_io)
            end
        end
        publish_sanitized_transcript!(raw_stdout, stdout_path)
        publish_sanitized_transcript!(raw_stderr, stderr_path)
        return result
    end
end

process_status(exit_code::Integer) = exit_code == 0 ? "PASS" : "FAIL"
process_score(exit_code::Integer) = exit_code == 0 ? 1.0 : 0.0

function process_command(pkg, kind::Symbol)
    if kind == :tests
        return "julia --startup-file=no --project=$pkg/test --code-coverage=user -e include(\"$pkg/test/runtests.jl\")"
    elseif kind == :docs
        return "julia --startup-file=no --project=$pkg/docs -e include(\"$pkg/docs/make.jl\")"
    end
    error("unsupported package process kind: $kind")
end

function canonical_process_check(pkg, kind::Symbol, exit_code::Integer,
                                 stdout_name::AbstractString,
                                 stderr_name::AbstractString,
                                 stdout_text::AbstractString,
                                 stderr_text::AbstractString)
    label = kind == :tests ? "tests" :
        kind == :docs ? "docs" : error("unsupported package process kind: $kind")
    io = IOBuffer()
    println(io, process_status(exit_code))
    println(io, "package: $pkg")
    println(io, "process: $label")
    println(io, "command: $(process_command(pkg, kind))")
    println(io, "exit_code: $exit_code")
    println(io, "stdout: $stdout_name")
    println(io, "stderr: $stderr_name")
    for (stream_label, contents) in
        (("captured stdout", stdout_text), ("captured stderr", stderr_text))
        println(io)
        println(io, "=== $stream_label ===")
        write(io, contents)
        isempty(contents) || endswith(contents, "\n") || println(io)
    end
    return String(take!(io))
end

function write_process_check(path, pkg, kind::Symbol, exit_code::Integer,
                             stdout_path, stderr_path)
    contents = canonical_process_check(
        pkg,
        kind,
        exit_code,
        basename(stdout_path),
        basename(stderr_path),
        read(stdout_path, String),
        read(stderr_path, String),
    )
    open(path, "w") do io
        write(io, contents)
    end
    return path
end

function validate_process_evidence(pkg, prefix, kind::Symbol, exit_code::Integer)
    suffix = kind == :tests ? "tests" :
        kind == :docs ? "docs" : error("unsupported package process kind: $kind")
    check_path = kind == :tests ? prefix * ".check.txt" : prefix * ".docs.check.txt"
    stdout_path = prefix * ".$suffix.stdout"
    stderr_path = prefix * ".$suffix.stderr"
    expected = canonical_process_check(
        pkg,
        kind,
        exit_code,
        basename(stdout_path),
        basename(stderr_path),
        read(stdout_path, String),
        read(stderr_path, String),
    )
    read(check_path, String) == expected ||
        error("$pkg $suffix check is not the canonical process record")
    return true
end

function validate_process_score_bindings(pkg, scores, test_exit_code::Integer,
                                         docs_exit_code::Integer)
    scores["testing"]["check"] == process_score(test_exit_code) ||
        error("$pkg testing.check does not match the recorded test exit code")
    scores["documentation"]["has_website"] == process_score(docs_exit_code) ||
        error("$pkg documentation score does not match the recorded docs exit code")
    return true
end

function run_package_tests(pkg, prefix)
    clean_coverage(pkg)
    stdout_path = prefix * ".tests.stdout"
    stderr_path = prefix * ".tests.stderr"
    test_file = joinpath(ROOT, pkg, "test", "runtests.jl")
    expression = "include($(repr(test_file)))"
    command = `$(Base.julia_cmd()) --startup-file=no --project=$(joinpath(ROOT, pkg, "test")) --code-coverage=user -e $expression`
    exit_code = capture_sanitized_transcripts(stdout_path, stderr_path) do stdout_io, stderr_io
        process = cd(ROOT) do
            run(pipeline(ignorestatus(command); stdout=stdout_io, stderr=stderr_io))
        end
        process.exitcode
    end
    write_process_check(
        prefix * ".check.txt", pkg, :tests, exit_code, stdout_path, stderr_path)
    return exit_code == 0, exit_code
end

function run_package_docs(pkg, prefix)
    stdout_path = prefix * ".docs.stdout"
    stderr_path = prefix * ".docs.stderr"
    check_path = prefix * ".docs.check.txt"
    docs_project = joinpath(ROOT, pkg, "docs")
    docs_file = joinpath(docs_project, "make.jl")
    build_dir = joinpath(docs_project, "build")
    isdir(build_dir) && rm(build_dir; recursive=true)

    exit_code = capture_sanitized_transcripts(stdout_path, stderr_path) do stdout_io, stderr_io
        if isfile(joinpath(docs_project, "Project.toml")) && isfile(docs_file)
            expression = "include($(repr(docs_file)))"
            command = `$(Base.julia_cmd()) --startup-file=no --project=$docs_project -e $expression`
            process = cd(ROOT) do
                run(pipeline(ignorestatus(command); stdout=stdout_io, stderr=stderr_io))
            end
            process.exitcode
        else
            println(stderr_io, "missing $pkg/docs/Project.toml or $pkg/docs/make.jl")
            1
        end
    end

    write_process_check(
        check_path, pkg, :docs, exit_code, stdout_path, stderr_path)
    return exit_code == 0, exit_code
end

function collect_coverage(pkg)
    source = joinpath(ROOT, pkg, "src")
    coverage = Coverage.process_folder(source)
    files = Any[]
    covered_lines = 0
    executable_lines = 0
    for file_coverage in coverage
        covered, executable = Coverage.get_summary(file_coverage)
        covered_lines += covered
        executable_lines += executable
        executable == 0 && continue
        push!(files, Dict(
            "file" => relpath(file_coverage.filename, joinpath(ROOT, pkg)),
            "coverage" => 100 * covered / executable,
        ))
    end
    sort!(files; by=item -> item["file"])
    overall = executable_lines == 0 ? 0.0 : 100 * covered_lines / executable_lines
    return Dict(
        "overall" => overall,
        "files" => files,
    ), Dict(
        "covered_lines" => covered_lines,
        "executable_lines" => executable_lines,
        "formula" => "100 * covered_lines / executable_lines",
    )
end

changelog_line_current(text, pkg, version) =
    any(line -> occursin(pkg, line) && occursin(version, line), eachline(IOBuffer(text)))

function changelog_status(pkg, version)
    path = joinpath(ROOT, "CHANGELOG.md")
    isfile(path) || return 0.0, 0.0
    text = read(path, String)
    current = changelog_line_current(text, pkg, version)
    return 1.0, current ? 1.0 : 0.0
end

function package_non_test_scores(pkg, docs_passed)
    project = package_project(pkg)
    has_news, news_current = changelog_status(pkg, string(project["version"]))
    authors = get(project, "authors", Any[])
    has_maintainer = authors isa AbstractVector && !isempty(authors)
    alpha_commit, _ = alpha_git_state()
    has_source_control = alpha_commit !== nothing
    bug_reports_url = strip(get(ENV, "QSPKIT_BUG_REPORTS_URL", ""))
    return Dict(
        "documentation" => Dict(
            "has_website" => docs_passed ? 1.0 : 0.0,
            "has_news" => has_news,
        ),
        "maintenance" => Dict(
            "has_maintainer" => has_maintainer ? 1.0 : 0.0,
            "news_current" => news_current,
        ),
        "transparency" => Dict(
            "has_source_control" => has_source_control ? 1.0 : 0.0,
            "has_bug_reports_url" => isempty(bug_reports_url) ? 0.0 : 1.0,
        ),
    )
end

function package_scores(pkg, passed, docs_passed, coverage_percent)
    result = package_non_test_scores(pkg, docs_passed)
    result["testing"] = Dict(
        "check" => passed ? 1.0 : 0.0,
        "coverage" => coverage_percent / 100,
    )
    return result
end

function alpha_git_state()
    isdir(joinpath(ROOT, ".git")) || return nothing, false
    try
        commit = strip(read(`git -C $ROOT rev-parse HEAD`, String))
        clean = isempty(strip(read(`git -C $ROOT status --porcelain`, String)))
        return commit, clean
    catch
        return nothing, false
    end
end

function release_commit(state=alpha_git_state())
    commit, clean = state
    commit === nothing && error("release evidence requires a Git repository with at least one commit")
    clean || error("release evidence requires a clean Git working tree")
    occursin(r"^[0-9a-f]{40}([0-9a-f]{24})?$", commit) ||
        error("release evidence requires a full Git commit object ID")
    return commit
end

function validate_release_source_info(source, expected_commit; require_workspace_archive=false)
    source["alpha_commit"] == expected_commit ||
        error("evidence alpha commit does not match current HEAD")
    source["alpha_worktree_clean"] === true ||
        error("evidence was not generated from a clean working tree")
    expected_mode = "git-archive:$expected_commit"
    source["archive_mode"] == expected_mode ||
        error("evidence source archive does not match current HEAD")
    if require_workspace_archive
        source["workspace_archive_mode"] == expected_mode ||
            error("evidence workspace archive does not match current HEAD")
    end
    return true
end

const WORKING_TREE_ARCHIVE_EXCLUDES = [
    ".git",
    "validation/cards",
    "validation/output",
    "Manifest.toml",
    "*/Manifest.toml",
    "docs/build",
    "*/docs/build",
    "docs/site",
    "*/docs/site",
    ".CondaPkg",
    "*/.CondaPkg",
    "LocalPreferences.toml",
    "*/LocalPreferences.toml",
    "JuliaLocalPreferences.toml",
    "*/JuliaLocalPreferences.toml",
    "logs",
    "*/logs",
    "artifacts",
    "*/artifacts",
    ".provenance",
    "*/.provenance",
    "*.cov",
    "*.jl.cov",
    "*.jl.*.cov",
    "*.log",
    "*.tmp",
    "*.bak",
    "*.aux",
    "*.toc",
    "Rplots.pdf",
    ".DS_Store",
    ".julia_history",
    "*/.julia_history",
    ".idea",
    "*/.idea",
    ".vscode",
    "*/.vscode",
]

function working_tree_archive(path, entries)
    arguments = String["tar", "-czf", path]
    append!(arguments, ["--exclude=$pattern" for pattern in WORKING_TREE_ARCHIVE_EXCLUDES])
    append!(arguments, ["-C", ROOT])
    append!(arguments, entries)
    run(Cmd(arguments))
end

function git_archive_command(commit; package=nothing, root=ROOT)
    arguments = String[
        "git", "-C", root, "-c", "tar.umask=0002", "archive", "--format=tar", commit,
    ]
    if package !== nothing
        append!(arguments, ["--", string(package)])
    end
    return Cmd(arguments)
end

function write_git_archive(path, commit; package=nothing, root=ROOT)
    mkpath(dirname(path))
    temporary, io = mktemp(dirname(path))
    try
        compression = pipeline(
            git_archive_command(commit; package, root),
            `gzip -n -9 -c`,
        )
        run(pipeline(compression; stdout=io))
        close(io)
        mv(temporary, path; force=true)
    catch
        isopen(io) && close(io)
        ispath(temporary) && rm(temporary; force=true)
        rethrow()
    end
    return path
end

function expected_git_archive_digest(commit; package=nothing, root=ROOT,
                                     cache=EXPECTED_ARCHIVE_DIGEST_CACHE)
    package_key = package === nothing ? "" : string(package)
    key = (realpath(root), string(commit), package_key)
    return get!(cache, key) do
        bytes2hex(sha256(read(git_archive_command(commit; package, root))))
    end
end

function decompressed_archive_digest(path)
    isfile(path) || error("source archive does not exist: $path")
    return bytes2hex(sha256(read(`gzip -dc $path`)))
end

function validate_git_archive(path, commit; package=nothing, root=ROOT,
                              cache=EXPECTED_ARCHIVE_DIGEST_CACHE)
    actual = decompressed_archive_digest(path)
    expected = expected_git_archive_digest(commit; package, root, cache)
    actual == expected || error(
        "source archive is not the canonical git archive for " *
        (package === nothing ? "the workspace" : string(package)) * " at $commit")
    return true
end

function write_source_archive(path; package=nothing, release=true)
    commit, clean = alpha_git_state()
    release && (commit = release_commit((commit, clean)); clean = true)
    if commit !== nothing && clean
        write_git_archive(path, commit; package)
        return "git-archive:$commit"
    end

    entries = if package === nothing
        candidates = [
            ".github", ".gitignore", "BACKPORTS.md", "CHANGELOG.md", "CONTRIBUTING.md",
            "CondaPkg.toml", "PROVENANCE.md", "README.md", "SANITIZATION.md",
            "SECURITY.md", "Project.toml",
            PACKAGES..., "validation",
        ]
        filter(entry -> ispath(joinpath(ROOT, entry)), candidates)
    else
        [package]
    end
    working_tree_archive(path, entries)
    return "working-tree"
end

function copy_resolved_manifest(source, destination)
    isfile(source) || error("resolved dependency manifest is missing: $(relpath(source, ROOT))")
    manifest = TOML.parsefile(source)
    get(manifest, "manifest_format", nothing) == "2.0" ||
        error("unsupported dependency manifest format in $(relpath(source, ROOT))")
    relative = relpath(source, ROOT)
    tracked = !isempty(read(Cmd(["git", "-C", ROOT, "ls-files", "--cached", "--", relative])))
    tracked && error("resolved dependency manifest must remain untracked: $relative")
    success(Cmd(["git", "-C", ROOT, "check-ignore", "-q", "--", relative])) ||
        error("resolved dependency manifest is not covered by the ignore policy: $relative")
    cp(source, destination; force=true)
    return destination
end

file_sha256(path) = open(path, "r") do io
    bytes2hex(sha256(io))
end

function current_project_resolve_hash(project_path)
    isfile(project_path) || error("manifest-binding Project.toml is missing: $project_path")
    project_file = abspath(project_path)
    project = Pkg.Types.read_project(project_file)
    workspace = if isempty(project.workspace)
        Dict{String, Pkg.Types.Project}()
    else
        collected = Pkg.Types.collect_workspace(project_file)
        delete!(collected, project_file)
        collected
    end
    manifest = Pkg.Types.Manifest()
    manifest_file = joinpath(dirname(project_file), "Manifest.toml")
    env = Pkg.Types.EnvCache(
        project_file,
        project_file,
        manifest_file,
        nothing,
        project,
        workspace,
        manifest,
        deepcopy(project),
        deepcopy(manifest),
    )
    return Pkg.Types.workspace_resolve_hash(env)
end

function resolved_manifest_binding(artifact_path, project_relative_path)
    manifest = TOML.parsefile(artifact_path)
    project_hash = get(manifest, "project_hash", nothing)
    project_hash isa AbstractString && occursin(r"^[0-9a-f]{40}$", project_hash) ||
        error("resolved manifest does not contain a valid project_hash")
    expected_hash = current_project_resolve_hash(joinpath(ROOT, project_relative_path))
    project_hash == expected_hash || error(
        "resolved manifest project_hash does not match the current $project_relative_path")
    return Dict(
        "artifact" => basename(artifact_path),
        "sha256" => file_sha256(artifact_path),
        "project_hash" => project_hash,
        "project_file" => replace(project_relative_path, '\\' => '/'),
        "policy" => MANIFEST_BINDING_POLICY,
    )
end

function validate_resolved_manifest_binding(binding, artifact_path,
                                            project_relative_path)
    require_exact_keys(
        binding,
        ["artifact", "sha256", "project_hash", "project_file", "policy"],
        "resolved manifest binding",
    )
    binding["artifact"] == basename(artifact_path) ||
        error("resolved manifest binding names the wrong artifact")
    binding["project_file"] == replace(project_relative_path, '\\' => '/') ||
        error("resolved manifest binding names the wrong Project.toml")
    binding["policy"] == MANIFEST_BINDING_POLICY ||
        error("resolved manifest binding has the wrong source-control policy")
    binding["sha256"] isa AbstractString &&
        occursin(r"^[0-9a-f]{64}$", binding["sha256"]) ||
        error("resolved manifest binding has an invalid SHA-256 digest")
    binding["sha256"] == file_sha256(artifact_path) ||
        error("resolved manifest SHA-256 does not match the evidence artifact")

    manifest = TOML.parsefile(artifact_path)
    get(manifest, "manifest_format", nothing) == "2.0" ||
        error("resolved manifest has an unsupported format")
    project_hash = get(manifest, "project_hash", nothing)
    binding["project_hash"] == project_hash ||
        error("resolved manifest project_hash does not match metadata")
    project_hash == current_project_resolve_hash(joinpath(ROOT, project_relative_path)) ||
        error("resolved manifest project_hash does not match the current Project.toml")
    return true
end

function source_metadata(archive_mode; workspace_archive_mode=nothing)
    alpha_commit, clean = alpha_git_state()
    metadata = Dict(
        "archive_mode" => archive_mode,
        "alpha_commit" => alpha_commit,
        "alpha_worktree_clean" => clean,
    )
    workspace_archive_mode === nothing ||
        (metadata["workspace_archive_mode"] = workspace_archive_mode)
    return metadata
end

function environment_metadata()
    bug_reports_url = strip(get(ENV, "QSPKIT_BUG_REPORTS_URL", ""))
    return Dict(
        "env_vars" => Dict(
            "QSPKIT_BUG_REPORTS_URL" => isempty(bug_reports_url) ? "not configured" : "configured",
        ),
        "sys" => Dict(
            "kernel" => string(Sys.KERNEL),
            "architecture" => string(Sys.ARCH),
            "Julia version" => string(VERSION),
        ),
    )
end

executor_label() = get(ENV, "GITHUB_ACTIONS", "") == "true" ? "github-actions" : "local"

function package_metadata(pkg, test_exit_code, docs_exit_code, details,
                          archive_mode, workspace_archive_mode, resolved_manifest)
    environment = environment_metadata()
    return Dict(
        "date" => Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ"),
        "executor" => executor_label(),
        "info" => Dict(
            "package" => pkg,
            "test_exit_code" => test_exit_code,
            "docs_exit_code" => docs_exit_code,
            "coverage_counts" => details,
            "resolved_manifest" => resolved_manifest,
            "source" => source_metadata(archive_mode; workspace_archive_mode),
            "julia_version" => string(VERSION),
            "env_vars" => environment["env_vars"],
            "sys" => environment["sys"],
        ),
    )
end

function package_descriptor(name, version)
    return Dict(
        "mpn_scorecard_format" => "1.0",
        "pkg_name" => name,
        "pkg_version" => version,
        "scorecard_type" => "julia",
    )
end

function write_package_comments(path, pkg, passed, docs_passed, details,
                                archive_mode, workspace_archive_mode)
    project = package_project(pkg)
    open(path, "w") do io
        println(io, "$pkg $(project["version"]) SDLC evidence")
        println(io)
        println(io, "Test check: ", passed ? "passed" : "failed", ".")
        println(io, "Documentation build: ", docs_passed ? "passed" : "failed", ".")
        println(io, "Coverage: $(details["covered_lines"])/$(details["executable_lines"]) executable source lines.")
        println(io, "Documentation credit requires a successful $pkg/docs/make.jl build; see the docs transcript.")
        println(io, "Release-note currency requires the package name and exact version together on one CHANGELOG.md line.")
        println(io, "A bug-report URL is credited only when QSPKIT_BUG_REPORTS_URL is configured.")
        println(io, "Source archive mode: $archive_mode.")
        println(io, "Workspace archive mode: $workspace_archive_mode.")
    end
end

function validate_score_schema(scores, coverage)
    Set(keys(scores)) == Set(REQUIRED_SCORE_CATEGORIES) ||
        error("score JSON categories do not match the external scorecard schema")
    expected_metrics = Dict(
        "testing" => Set(["check", "coverage"]),
        "documentation" => Set(["has_website", "has_news"]),
        "maintenance" => Set(["has_maintainer", "news_current"]),
        "transparency" => Set(["has_source_control", "has_bug_reports_url"]),
    )
    for category in REQUIRED_SCORE_CATEGORIES
        scores[category] isa AbstractDict || error("$category scores are not a mapping")
        Set(keys(scores[category])) == expected_metrics[category] ||
            error("$category score metrics do not match the schema")
    end
    require_exact_keys(coverage, ["overall", "files"], "coverage JSON")
    coverage["overall"] isa Real || error("coverage.overall is not numeric")
    coverage["files"] isa AbstractVector || error("coverage.files is not a list")
    for (index, file) in pairs(coverage["files"])
        require_exact_keys(file, ["file", "coverage"], "coverage.files[$index]")
        file["file"] isa AbstractString || error("coverage file path is not text")
        file["coverage"] isa Real || error("coverage file percentage is not numeric")
        0 <= file["coverage"] <= 100 || error("coverage file percentage is outside [0, 100]")
    end
    check = scores["testing"]["check"]
    check in (0, 0.0, 1, 1.0) || error("testing.check must be 0 or 1")
    expected = coverage["overall"] / 100
    isapprox(scores["testing"]["coverage"], expected; atol=1e-12, rtol=0) ||
        error("testing.coverage does not match coverage.overall / 100")
    for category in values(scores), value in values(category)
        value isa Real || error("all score values must be numeric")
        0 <= value <= 1 || error("score value is outside [0, 1]: $value")
    end
    return true
end

function validate_public_text_artifact(path)
    relative = relpath(path, ROOT)
    findings = scan_file(path, relative)
    isempty(findings) || throw(sanitization_error("evidence text privacy scan", findings))
    return validate_public_text_payload(read(path, String), relative)
end

function require_exact_keys(payload, expected, label)
    payload isa AbstractDict || error("$label is not a mapping")
    Set(keys(payload)) == Set(expected) || error("$label fields do not match the schema")
    return true
end

function validate_environment_metadata_payload(metadata, label; kind=:package)
    kind in (:package, :aggregate) || error("unsupported metadata kind: $kind")
    require_exact_keys(metadata, ["date", "executor", "info"], "$label metadata")
    metadata["date"] isa AbstractString &&
        occursin(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", metadata["date"]) ||
        error("$label metadata date is not a UTC timestamp")
    metadata["executor"] in ("local", "github-actions") ||
        error("$label metadata has an identifying executor value")
    info = metadata["info"]
    expected_info = kind == :package ? [
        "package", "test_exit_code", "docs_exit_code", "coverage_counts",
        "resolved_manifest", "source", "julia_version", "env_vars", "sys",
    ] : [
        "julia_version", "coverage_counts", "resolved_manifest", "source",
        "env_vars", "sys",
    ]
    require_exact_keys(info, expected_info, "$label metadata.info")
    env_vars = info["env_vars"]
    require_exact_keys(
        env_vars, ["QSPKIT_BUG_REPORTS_URL"], "$label metadata.info.env_vars")
    env_vars["QSPKIT_BUG_REPORTS_URL"] in ("configured", "not configured") ||
        error("$label metadata exposes the bug-report URL")
    sys = info["sys"]
    require_exact_keys(
        sys, ["kernel", "architecture", "Julia version"], "$label metadata.info.sys")
    all(value -> value isa AbstractString, values(sys)) ||
        error("$label metadata system values are not text")
    counts = info["coverage_counts"]
    require_exact_keys(
        counts, ["covered_lines", "executable_lines", "formula"],
        "$label metadata.info.coverage_counts")
    counts["covered_lines"] isa Integer && counts["covered_lines"] >= 0 ||
        error("$label covered-line metadata is invalid")
    counts["executable_lines"] isa Integer && counts["executable_lines"] >= 0 ||
        error("$label executable-line metadata is invalid")
    counts["formula"] isa AbstractString || error("$label coverage formula is not text")
    resolved_manifest = info["resolved_manifest"]
    require_exact_keys(
        resolved_manifest,
        ["artifact", "sha256", "project_hash", "project_file", "policy"],
        "$label metadata.info.resolved_manifest",
    )
    all(value -> value isa AbstractString, values(resolved_manifest)) ||
        error("$label resolved-manifest metadata values are not text")
    occursin(r"^[0-9a-f]{64}$", resolved_manifest["sha256"]) ||
        error("$label resolved-manifest SHA-256 is invalid")
    occursin(r"^[0-9a-f]{40}$", resolved_manifest["project_hash"]) ||
        error("$label resolved-manifest project hash is invalid")
    resolved_manifest["policy"] == MANIFEST_BINDING_POLICY ||
        error("$label resolved-manifest policy is invalid")
    source = info["source"]
    source_fields = ["archive_mode", "alpha_commit", "alpha_worktree_clean"]
    kind == :package && push!(source_fields, "workspace_archive_mode")
    require_exact_keys(source, source_fields, "$label metadata.info.source")
    source["archive_mode"] isa AbstractString ||
        error("$label archive mode is not text")
    source["alpha_commit"] === nothing || source["alpha_commit"] isa AbstractString ||
        error("$label alpha commit metadata is invalid")
    source["alpha_worktree_clean"] isa Bool ||
        error("$label clean-tree metadata is invalid")
    kind == :package && !(source["workspace_archive_mode"] isa AbstractString) &&
        error("$label workspace archive mode is not text")
    info["julia_version"] isa AbstractString ||
        error("$label metadata Julia version is not text")
    if kind == :package
        info["package"] isa AbstractString && info["package"] == label ||
            error("$label metadata package mismatch")
        info["test_exit_code"] isa Integer || error("$label test exit code is not an integer")
        info["docs_exit_code"] isa Integer || error("$label docs exit code is not an integer")
    end
    return true
end

function validate_result(name, version, prefix)
    required = [
        prefix * ".pkg.json",
        prefix * ".check.txt",
        prefix * ".coverage.json",
        prefix * ".scores.json",
        prefix * ".metadata.json",
        prefix * ".matrix.yaml",
        prefix * ".tar.gz",
    ]
    for path in required
        isfile(path) || error("missing scorecard artifact: $(relpath(path, ROOT))")
        filesize(path) > 0 || error("empty scorecard artifact: $(relpath(path, ROOT))")
    end
    descriptor = JSON.parsefile(prefix * ".pkg.json")
    require_exact_keys(
        descriptor,
        ["mpn_scorecard_format", "pkg_name", "pkg_version", "scorecard_type"],
        "$name package descriptor",
    )
    descriptor["mpn_scorecard_format"] == "1.0" || error("unexpected scorecard format")
    descriptor["pkg_name"] == name || error("scorecard package-name mismatch")
    descriptor["pkg_version"] == version || error("scorecard version mismatch")
    descriptor["scorecard_type"] == "julia" || error("unexpected scorecard type")
    coverage = JSON.parsefile(prefix * ".coverage.json")
    scores = JSON.parsefile(prefix * ".scores.json")
    validate_score_schema(scores, coverage)
    for path in required
        endswith(path, ".tar.gz") || validate_public_text_artifact(path)
    end
    return true
end

function validate_package_result(pkg; release=true, expected_commit=nothing)
    prefix = result_prefix(pkg)
    validate_result(pkg, package_version(pkg), prefix)
    extras = [
        prefix * ".coverage-details.json",
        prefix * ".tests.stdout",
        prefix * ".tests.stderr",
        prefix * ".docs.check.txt",
        prefix * ".docs.stdout",
        prefix * ".docs.stderr",
        prefix * ".comments.txt",
        prefix * ".test.Manifest.toml",
        prefix * ".workspace.tar.gz",
    ]
    for path in extras
        isfile(path) || error("missing package evidence: $(relpath(path, ROOT))")
        endswith(path, ".tar.gz") || validate_public_text_artifact(path)
    end
    coverage = JSON.parsefile(prefix * ".coverage.json")
    details = JSON.parsefile(prefix * ".coverage-details.json")
    require_exact_keys(
        details,
        ["covered_lines", "executable_lines", "formula"],
        "$pkg coverage details",
    )
    details["formula"] == "100 * covered_lines / executable_lines" ||
        error("$pkg coverage formula is not canonical")
    details["covered_lines"] isa Integer && details["covered_lines"] >= 0 ||
        error("$pkg covered-line count is invalid")
    details["executable_lines"] isa Integer && details["executable_lines"] >= 0 ||
        error("$pkg executable-line count is invalid")
    details["covered_lines"] <= details["executable_lines"] ||
        error("$pkg covered-line count exceeds executable lines")
    _, _, expected = weighted_coverage([details])
    isapprox(coverage["overall"], expected; atol=1e-12, rtol=0) ||
        error("$pkg coverage counts do not reproduce coverage.overall")
    metadata = JSON.parsefile(prefix * ".metadata.json")
    validate_environment_metadata_payload(metadata, pkg)
    info = metadata["info"]
    info["coverage_counts"] == details ||
        error("$pkg metadata coverage counts do not exactly match coverage details")
    info["julia_version"] == info["sys"]["Julia version"] == string(VERSION) ||
        error("$pkg metadata Julia version does not match the verifier")

    test_exit_code = info["test_exit_code"]
    docs_exit_code = info["docs_exit_code"]
    validate_process_evidence(pkg, prefix, :tests, test_exit_code)
    validate_process_evidence(pkg, prefix, :docs, docs_exit_code)
    test_passed = test_exit_code == 0
    docs_passed = docs_exit_code == 0
    scores = JSON.parsefile(prefix * ".scores.json")
    validate_process_score_bindings(pkg, scores, test_exit_code, docs_exit_code)
    scores == package_scores(pkg, test_passed, docs_passed, coverage["overall"]) ||
        error("$pkg scores do not exactly match the current evidence inputs")

    manifest_artifact = prefix * ".test.Manifest.toml"
    validate_resolved_manifest_binding(
        info["resolved_manifest"],
        manifest_artifact,
        joinpath(pkg, "test", "Project.toml"),
    )

    commit = nothing
    if release
        commit = expected_commit === nothing ? release_commit() : expected_commit
        validate_release_source_info(
            info["source"], commit; require_workspace_archive=true)
        validate_git_archive(prefix * ".tar.gz", commit; package=pkg)
        validate_git_archive(prefix * ".workspace.tar.gz", commit)
    end
    validate_package_matrix_copy(prefix * ".matrix.yaml", pkg; release, commit)
    return true
end

function generate_package(pkg; release=true)
    validate_release_sanitization()
    pkg in PACKAGES || error("unsupported package `$pkg`; expected one of $(join(PACKAGES, ", "))")
    expected_commit = release ? release_commit() : nothing
    validate_matrix(pkg)
    dir = result_dir(pkg)
    isdir(dir) && rm(dir; recursive=true)
    mkpath(dir)
    prefix = result_prefix(pkg)
    passed, test_exit_code = run_package_tests(pkg, prefix)
    docs_passed, docs_exit_code = run_package_docs(pkg, prefix)
    coverage, details = collect_coverage(pkg)
    scores = package_scores(pkg, passed, docs_passed, coverage["overall"])
    version = package_version(pkg)
    archive_mode = write_source_archive(prefix * ".tar.gz"; package=pkg, release)
    workspace_archive_mode = write_source_archive(prefix * ".workspace.tar.gz"; release)
    manifest_artifact = prefix * ".test.Manifest.toml"
    copy_resolved_manifest(
        joinpath(ROOT, pkg, "test", "Manifest.toml"),
        manifest_artifact,
    )
    manifest_binding = resolved_manifest_binding(
        manifest_artifact, joinpath(pkg, "test", "Project.toml"))

    cp(matrix_path(pkg), prefix * ".matrix.yaml"; force=true)
    json_file(prefix * ".pkg.json", package_descriptor(pkg, version))
    json_file(prefix * ".coverage.json", coverage)
    json_file(prefix * ".coverage-details.json", details)
    json_file(prefix * ".scores.json", scores)
    json_file(prefix * ".metadata.json",
        package_metadata(pkg, test_exit_code, docs_exit_code, details,
            archive_mode, workspace_archive_mode, manifest_binding))
    write_package_comments(prefix * ".comments.txt", pkg, passed, docs_passed, details,
        archive_mode, workspace_archive_mode)
    validate_package_result(pkg; release, expected_commit)

    qualified = passed && docs_passed
    status = qualified ? "PASS" : "FAIL"
    docs_status = docs_passed ? "PASS" : "FAIL"
    println("$status $pkg $(version): $(details["covered_lines"])/$(details["executable_lines"]) executable lines covered; docs $docs_status")
    return qualified
end

score_mean(components, category, metric) =
    sum(component["scores"][category][metric] for component in components) / length(components)

function weighted_coverage(counts)
    covered = sum(item["covered_lines"] for item in counts; init=0)
    executable = sum(item["executable_lines"] for item in counts; init=0)
    percent = executable == 0 ? 0.0 : 100 * covered / executable
    return covered, executable, percent
end

function missing_component(pkg)
    scores = Dict(
        "testing" => Dict("check" => 0.0, "coverage" => 0.0),
        "documentation" => Dict("has_website" => 0.0, "has_news" => 0.0),
        "maintenance" => Dict("has_maintainer" => 0.0, "news_current" => 0.0),
        "transparency" => Dict("has_source_control" => 0.0, "has_bug_reports_url" => 0.0),
    )
    return Dict(
        "package" => pkg,
        "version" => package_version(pkg),
        "status" => "missing",
        "scores" => scores,
        "coverage_counts" => Dict("covered_lines" => 0, "executable_lines" => 0),
    )
end

function load_component(pkg; release=true, expected_commit=nothing)
    prefix = result_prefix(pkg)
    if !isdir(result_dir(pkg))
        release && error("release aggregate is missing the $pkg component card")
        return missing_component(pkg)
    end
    try
        validate_package_result(pkg; release, expected_commit)
        return Dict(
            "package" => pkg,
            "version" => package_version(pkg),
            "status" => "available",
            "scores" => JSON.parsefile(prefix * ".scores.json"),
            "coverage_counts" => JSON.parsefile(prefix * ".coverage-details.json"),
        )
    catch err
        release && rethrow()
        component = missing_component(pkg)
        component["status"] = "invalid: $(sprint(showerror, err))"
        return component
    end
end

yaml_string(value) = JSON.json(string(value))

function aggregate_matrix_text(; packages=PACKAGES, matrix_reader=read_matrix)
    io = IOBuffer()
    println(io, "# Generated from the validated package matrices. Do not edit this file directly.")
    for pkg in packages
        for row in matrix_reader(pkg)
            println(io, "- entrypoint: ", yaml_string("$pkg.$(row["entrypoint"])"))
            println(io, "  code: ", yaml_string(joinpath(pkg, row["code"])))
            println(io, "  doc: ", yaml_string(joinpath(pkg, row["doc"])))
            println(io, "  tests:")
            for test in row["tests"]
                println(io, "    - ", yaml_string(joinpath(pkg, test)))
            end
        end
    end
    return String(take!(io))
end

function write_aggregate_matrix(path)
    open(path, "w") do io
        write(io, aggregate_matrix_text())
    end
    return path
end

function validate_aggregate_matrix_copy(path)
    read(path, String) == aggregate_matrix_text() ||
        error("aggregate matrix does not exactly regenerate from the current package matrices")
    return true
end

function aggregate_coverage_files(components)
    all(component -> component["status"] == "available", components) || return Any[]
    files = Any[]
    for component in components
        component["status"] == "available" || continue
        pkg = component["package"]
        coverage = JSON.parsefile(result_prefix(pkg) * ".coverage.json")
        for file in coverage["files"]
            push!(files, Dict(
                "file" => joinpath(pkg, file["file"]),
                "coverage" => file["coverage"],
            ))
        end
    end
    sort!(files; by=item -> item["file"])
    return files
end

function aggregate_coverage(components)
    counts = [component["coverage_counts"] for component in components]
    if !all(component -> component["status"] == "available", components)
        executable = sum(item["executable_lines"] for item in counts; init=0)
        return 0, executable, 0.0
    end
    return weighted_coverage(counts)
end

function aggregate_scores(components, coverage_percent)
    checks = [component["scores"]["testing"]["check"] for component in components]
    return Dict(
        "testing" => Dict(
            "check" => minimum(checks),
            "coverage" => coverage_percent / 100,
        ),
        "documentation" => Dict(
            "has_website" => score_mean(components, "documentation", "has_website"),
            "has_news" => score_mean(components, "documentation", "has_news"),
        ),
        "maintenance" => Dict(
            "has_maintainer" => score_mean(components, "maintenance", "has_maintainer"),
            "news_current" => score_mean(components, "maintenance", "news_current"),
        ),
        "transparency" => Dict(
            "has_source_control" => score_mean(components, "transparency", "has_source_control"),
            "has_bug_reports_url" => score_mean(components, "transparency", "has_bug_reports_url"),
        ),
    )
end

function validate_aggregate_scores(scores, components, coverage_percent)
    expected = aggregate_scores(components, coverage_percent)
    Set(keys(scores)) == Set(keys(expected)) ||
        error("aggregate score categories do not match recomputed categories")
    for (category, metrics) in expected
        Set(keys(scores[category])) == Set(keys(metrics)) ||
            error("aggregate $category metrics do not match recomputed metrics")
        for (metric, value) in metrics
            isapprox(scores[category][metric], value; atol=1e-12, rtol=0) ||
                error("aggregate $category.$metric does not match the component artifacts")
        end
    end
    return true
end

function validate_component_snapshot(component, pkg, version, actual_scores, actual_counts)
    require_exact_keys(
        component,
        ["package", "version", "status", "scores", "coverage_counts"],
        "aggregate component $pkg",
    )
    component["package"] == pkg || error("aggregate component package mismatch for $pkg")
    component["version"] == version ||
        error("aggregate component version mismatch for $pkg")
    component["status"] == "available" ||
        error("aggregate component $pkg is not available")

    component["scores"] == actual_scores ||
        error("aggregate component scores are stale or altered for $pkg")
    component["coverage_counts"] == actual_counts ||
        error("aggregate component coverage counts are stale or altered for $pkg")
    return true
end

function validate_component_binding(component, pkg)
    actual_scores = JSON.parsefile(result_prefix(pkg) * ".scores.json")
    actual_counts = JSON.parsefile(result_prefix(pkg) * ".coverage-details.json")
    return validate_component_snapshot(
        component, pkg, package_version(pkg), actual_scores, actual_counts)
end

function validate_unavailable_component(component, pkg)
    expected = missing_component(pkg)
    require_exact_keys(
        component,
        ["package", "version", "status", "scores", "coverage_counts"],
        "development aggregate component $pkg",
    )
    component["package"] == expected["package"] ||
        error("development aggregate component package mismatch for $pkg")
    component["version"] == expected["version"] ||
        error("development aggregate component version mismatch for $pkg")
    status = component["status"]
    (status == "missing" || startswith(status, "invalid: ")) ||
        error("development aggregate component $pkg has an unsupported status")
    component["scores"] == expected["scores"] ||
        error("development aggregate component $pkg does not use fail-closed zero scores")
    component["coverage_counts"] == expected["coverage_counts"] ||
        error("development aggregate component $pkg does not use fail-closed zero coverage")
    return true
end

aggregate_formulas() = Dict(
    "testing.check" => "minimum component check; every component must pass",
    "testing.coverage" => "zero if any component is missing/invalid; otherwise sum covered executable lines / sum executable lines",
    "other_metrics" => "arithmetic mean across all component metric values",
    "missing_or_invalid_component" => "all component metric values and coverage counts are zero",
)

function component_check_texts(components)
    return Dict(
        component["package"] => begin
            path = result_prefix(component["package"]) * ".check.txt"
            isfile(path) ? read(path, String) : ""
        end
        for component in components
    )
end

function canonical_aggregate_check(components, checks)
    io = IOBuffer()
    passed = all(
        component -> component["status"] == "available" &&
            component["scores"]["testing"]["check"] == 1,
        components,
    )
    println(io, passed ? "PASS" : "FAIL")
    println(io, "rule: every component package check must pass")
    for component in components
        pkg = component["package"]
        haskey(checks, pkg) || error("aggregate check is missing the $pkg check text")
        check = component["scores"]["testing"]["check"]
        println(io, "$pkg: $(check == 1 ? "PASS" : "FAIL") ($(component["status"]))")
    end
    for component in components
        pkg = component["package"]
        println(io)
        println(io, "===== BEGIN $pkg CHECK =====")
        contents = checks[pkg]
        if isempty(contents)
            println(io, "No component check artifact was available.")
        else
            write(io, contents)
            endswith(contents, "\n") || println(io)
        end
        println(io, "===== END $pkg CHECK =====")
    end
    return String(take!(io))
end

function write_aggregate_check(path, components)
    text = canonical_aggregate_check(components, component_check_texts(components))
    open(path, "w") do io
        write(io, text)
    end
    return path
end

function validate_aggregate_check(path, components)
    expected = canonical_aggregate_check(components, component_check_texts(components))
    read(path, String) == expected ||
        error("aggregate check does not exactly bind the current component checks and statuses")
    return true
end

function generate_aggregate(; release=true)
    validate_release_sanitization()
    expected_commit = release ? release_commit() : nothing
    components = [load_component(pkg; release, expected_commit) for pkg in PACKAGES]
    covered, executable, percent = aggregate_coverage(components)
    scores = aggregate_scores(components, percent)
    passed = scores["testing"]["check"] == 1

    dir = aggregate_result_dir()
    isdir(dir) && rm(dir; recursive=true)
    mkpath(dir)
    prefix = aggregate_prefix()
    coverage = Dict("overall" => percent, "files" => aggregate_coverage_files(components))
    details = Dict(
        "covered_lines" => covered,
        "executable_lines" => executable,
        "formula" => "0 when any component is missing/invalid; otherwise 100 * sum(component covered_lines) / sum(component executable_lines)",
    )
    breakdown = Dict(
        "aggregate" => AGGREGATE_NAME,
        "version" => AGGREGATE_VERSION,
        "components" => components,
        "formulas" => aggregate_formulas(),
    )

    archive_mode = write_source_archive(prefix * ".tar.gz"; release)
    manifest_artifact = prefix * ".workspace.Manifest.toml"
    copy_resolved_manifest(joinpath(ROOT, "Manifest.toml"), manifest_artifact)
    manifest_binding = resolved_manifest_binding(manifest_artifact, "Project.toml")
    json_file(prefix * ".pkg.json", package_descriptor(AGGREGATE_NAME, AGGREGATE_VERSION))
    json_file(prefix * ".coverage.json", coverage)
    json_file(prefix * ".coverage-details.json", details)
    json_file(prefix * ".scores.json", scores)
    json_file(prefix * ".components.json", breakdown)
    environment = environment_metadata()
    json_file(prefix * ".metadata.json", Dict(
        "date" => Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ"),
        "executor" => executor_label(),
        "info" => Dict(
            "julia_version" => string(VERSION),
            "coverage_counts" => details,
            "resolved_manifest" => manifest_binding,
            "source" => source_metadata(archive_mode),
            "env_vars" => environment["env_vars"],
            "sys" => environment["sys"],
        ),
    ))
    write_aggregate_matrix(prefix * ".matrix.yaml")
    write_aggregate_check(prefix * ".check.txt", components)
    open(prefix * ".comments.txt", "w") do io
        println(io, "QSPKit whole-workspace SDLC evidence")
        println(io)
        println(io, "The aggregate check is fail-closed: all $(length(PACKAGES)) component checks must equal 1.")
        println(io, "Coverage is forced to zero if any component is missing/invalid; otherwise it is executable-line-weighted ($(covered)/$(executable)), never an average of package percentages.")
        println(io, "Documentation, maintenance, and transparency metrics are arithmetic means of component values.")
        println(io, "See $(basename(prefix)).components.json for the component scores, counts, statuses, and formulas.")
        println(io, "Source archive mode: $archive_mode.")
    end
    validate_aggregate_result(; release, expected_commit)
    println("$(passed ? "PASS" : "FAIL") QSPKit aggregate: $covered/$executable executable lines covered")
    return passed
end

function validate_aggregate_result(; release=true, expected_commit=nothing)
    prefix = aggregate_prefix()
    commit = release ?
        (expected_commit === nothing ? release_commit() : expected_commit) : nothing
    validate_result(AGGREGATE_NAME, AGGREGATE_VERSION, prefix)
    extras = [
        prefix * ".coverage-details.json",
        prefix * ".components.json",
        prefix * ".comments.txt",
        prefix * ".workspace.Manifest.toml",
    ]
    for path in extras
        isfile(path) || error("missing aggregate evidence: $(relpath(path, ROOT))")
        validate_public_text_artifact(path)
    end
    breakdown = JSON.parsefile(prefix * ".components.json")
    require_exact_keys(
        breakdown,
        ["aggregate", "version", "components", "formulas"],
        "aggregate component breakdown",
    )
    breakdown["aggregate"] == AGGREGATE_NAME ||
        error("aggregate component breakdown has the wrong name")
    breakdown["version"] == AGGREGATE_VERSION ||
        error("aggregate component breakdown has the wrong version")
    breakdown["formulas"] == aggregate_formulas() ||
        error("aggregate component formulas are stale or altered")
    components = breakdown["components"]
    components isa AbstractVector || error("aggregate components are not a list")
    [component["package"] for component in components] == PACKAGES ||
        error("aggregate component order or membership is incorrect")
    for (component, pkg) in zip(components, PACKAGES)
        if component["status"] == "available"
            validate_package_result(pkg; release, expected_commit=commit)
            validate_component_binding(component, pkg)
        elseif release
            error("release aggregate component $pkg is not available")
        else
            validate_unavailable_component(component, pkg)
        end
    end
    covered, executable, percent = aggregate_coverage(components)
    details = JSON.parsefile(prefix * ".coverage-details.json")
    require_exact_keys(
        details,
        ["covered_lines", "executable_lines", "formula"],
        "aggregate coverage details",
    )
    details["formula"] == "0 when any component is missing/invalid; otherwise 100 * sum(component covered_lines) / sum(component executable_lines)" ||
        error("aggregate coverage formula is stale or altered")
    details["covered_lines"] == covered || error("aggregate covered-line count mismatch")
    details["executable_lines"] == executable || error("aggregate executable-line count mismatch")
    coverage = JSON.parsefile(prefix * ".coverage.json")
    isapprox(coverage["overall"], percent; atol=1e-12, rtol=0) ||
        error("aggregate coverage is not executable-line-weighted")
    scores = JSON.parsefile(prefix * ".scores.json")
    validate_aggregate_scores(scores, components, percent)
    validate_aggregate_check(prefix * ".check.txt", components)
    validate_aggregate_matrix_copy(prefix * ".matrix.yaml")
    metadata = JSON.parsefile(prefix * ".metadata.json")
    validate_environment_metadata_payload(metadata, AGGREGATE_NAME; kind=:aggregate)
    info = metadata["info"]
    info["coverage_counts"] == details ||
        error("aggregate metadata coverage counts do not exactly match coverage details")
    info["julia_version"] == info["sys"]["Julia version"] == string(VERSION) ||
        error("aggregate metadata Julia version does not match the verifier")
    validate_resolved_manifest_binding(
        info["resolved_manifest"],
        prefix * ".workspace.Manifest.toml",
        "Project.toml",
    )
    if release
        validate_release_source_info(info["source"], commit)
        validate_git_archive(prefix * ".tar.gz", commit)
    end
    return true
end

function verify_all_results(; release=true)
    validate_release_sanitization()
    expected_commit = release ? release_commit() : nothing
    for pkg in PACKAGES
        validate_package_result(pkg; release, expected_commit)
    end
    validate_aggregate_result(; release, expected_commit)
    println("validated all package and aggregate external scorecard artifacts")
    return true
end

function recognized_evidence_archive(path)
    result_name = basename(dirname(path))
    filename = basename(path)
    return filename in (
        result_name * ".tar.gz",
        result_name * ".workspace.tar.gz",
    )
end

expected_scorecard_result_names() = [
    [result_name(pkg) for pkg in PACKAGES]...,
    aggregate_result_name(),
]

expected_scorecard_pdf_names() = [
    result * ".scorecard.pdf" for result in expected_scorecard_result_names()
]

function pdf_utility_executable(default_name, override)
    executable = if override === nothing
        Sys.which(default_name)
    else
        candidate = String(override)
        isfile(candidate) ? candidate : Sys.which(candidate)
    end
    executable === nothing && error(
        "$default_name is required for rendered-scorecard privacy validation")
    return executable
end

function run_pdf_utility(arguments, output_path, label)
    stderr_path = output_path * ".stderr"
    process = open(stderr_path, "w") do stderr_io
        open(output_path, "w") do output_io
            run(pipeline(
                ignorestatus(Cmd(arguments)),
                stdout=output_io,
                stderr=stderr_io,
            ))
        end
    end
    success(process) || error("$label failed for a rendered scorecard")
    return true
end

function extract_pdf_text(pdf_path, text_path; extractor=nothing)
    if extractor isa Function
        extractor(pdf_path, text_path)
        return true
    end
    executable = pdf_utility_executable("pdftotext", extractor)
    stderr_path = text_path * ".stderr"
    process = open(stderr_path, "w") do stderr_io
        run(pipeline(
            ignorestatus(Cmd([
                executable,
                "-enc", "UTF-8",
                "-nopgbrk",
                pdf_path,
                text_path,
            ])),
            stdout=devnull,
            stderr=stderr_io,
        ))
    end
    success(process) || error("pdftotext failed for a rendered scorecard")
    return true
end

function extract_pdf_metadata(pdf_path, metadata_path; extractor=nothing)
    if extractor isa Function
        extractor(pdf_path, metadata_path)
        return true
    end
    executable = pdf_utility_executable("pdfinfo", extractor)
    info_path = metadata_path * ".info"
    xmp_path = metadata_path * ".xmp"
    run_pdf_utility([executable, pdf_path], info_path, "pdfinfo")
    filesize(info_path) > 0 || error("pdfinfo produced empty PDF Info output")
    run_pdf_utility([executable, "-meta", pdf_path], xmp_path, "pdfinfo -meta")
    open(metadata_path, "w") do io
        println(io, "===== PDF INFO =====")
        write(io, read(info_path))
        println(io)
        println(io, "===== XMP METADATA =====")
        write(io, read(xmp_path))
    end
    return true
end

function validate_rendered_scorecard_privacy(
        cards_root=CARDS;
        expected_names=expected_scorecard_pdf_names(),
        extractor=nothing,
        metadata_extractor=nothing)
    isdir(cards_root) || error("rendered-scorecard directory is missing")
    islink(cards_root) && error("rendered-scorecard directory is a symbolic link")
    expected = sort!(unique!(String.(expected_names)))
    length(expected) == length(expected_names) ||
        error("expected rendered-scorecard filenames contain duplicates")
    actual = sort!(readdir(cards_root))
    actual == expected || error(
        "rendered-scorecard directory does not contain exactly the expected PDFs")

    mktempdir() do extraction_root
        for filename in expected
            endswith(filename, ".scorecard.pdf") || error(
                "unexpected rendered-scorecard filename")
            relative = joinpath("validation", "cards", filename)
            findings = scan_text("", relative)
            isempty(findings) || throw(sanitization_error(
                "rendered-scorecard filename privacy scan", findings))

            pdf_path = joinpath(cards_root, filename)
            islink(pdf_path) && error("rendered scorecard is a symbolic link")
            isfile(pdf_path) || error("rendered scorecard is not a regular file")
            filesize(pdf_path) > 5 || error("rendered scorecard is empty")
            signature = open(pdf_path, "r") do io
                read(io, 5)
            end
            signature == collect(codeunits("%PDF-")) || error(
                "rendered scorecard does not have a PDF signature")

            text_path = joinpath(extraction_root, filename * ".txt")
            extract_pdf_text(pdf_path, text_path; extractor)
            islink(text_path) && error("PDF text extraction produced a symbolic link")
            isfile(text_path) || error("PDF text extraction did not produce a text file")
            filesize(text_path) > 0 || error("PDF text extraction produced empty output")
            text_findings = scan_file(
                text_path,
                relative * ".txt";
                allowed_non_text_paths=Set{String}(),
            )
            isempty(text_findings) || throw(sanitization_error(
                "rendered-scorecard text privacy scan", text_findings))
            text = read(text_path, String)
            isempty(strip(text)) && error(
                "PDF text extraction produced no visible text")
            validate_public_text_payload(text, "rendered scorecard $filename")

            metadata_path = joinpath(extraction_root, filename * ".metadata.txt")
            extract_pdf_metadata(
                pdf_path, metadata_path; extractor=metadata_extractor)
            islink(metadata_path) && error(
                "PDF metadata extraction produced a symbolic link")
            isfile(metadata_path) || error(
                "PDF metadata extraction did not produce a text file")
            filesize(metadata_path) > 0 || error(
                "PDF metadata extraction produced empty output")
            metadata_findings = scan_file(
                metadata_path,
                relative * ".metadata.txt";
                allowed_non_text_paths=Set{String}(),
            )
            isempty(metadata_findings) || throw(sanitization_error(
                "rendered-scorecard metadata privacy scan", metadata_findings))
            metadata = read(metadata_path, String)
            isempty(strip(metadata)) && error(
                "PDF metadata extraction produced no visible text")
            validate_public_text_payload(
                metadata, "rendered scorecard metadata $filename")
        end
    end
    println(
        "validated extracted text and metadata privacy for $(length(expected)) scorecard PDFs")
    return true
end

function validate_output_privacy(output_root=OUTPUT)
    isdir(output_root) || return true
    for (dir, dirs, files) in walkdir(output_root)
        for directory in dirs
            path = joinpath(dir, directory)
            islink(path) && error(
                "evidence output contains a symbolic link: $(relpath(path, ROOT))")
        end
        for file in files
            path = joinpath(dir, file)
            relative = relpath(path, ROOT)
            islink(path) && error("evidence output contains a symbolic link: $relative")
            isfile(path) || error("evidence output contains an unsupported file: $relative")
            if recognized_evidence_archive(path)
                isempty(scan_text("", relative)) ||
                    throw(sanitization_error("evidence filename privacy scan", scan_text("", relative)))
            else
                validate_public_text_artifact(path)
            end
        end
    end
    println("validated scorecard output privacy")
    return true
end

function clean_generated(; root=ROOT, packages=PACKAGES)
    removed = 0
    removed += remove_generated_path(joinpath(root, "validation", "output"))
    removed += remove_generated_path(joinpath(root, "validation", "cards"))
    for pkg in packages
        clean_coverage(pkg; root)
    end
    removed += clean_environment_artifacts(; root, packages)
    println("removed generated scorecard evidence, PDFs, coverage sidecars, " *
            "manifests, documentation builds, and local package-manager state " *
            "($removed top-level artifacts)")
    return removed
end

function usage(io=stdout)
    println(io, "usage: julia --project=validation validation/generate.jl <command> [package]")
    println(io, "release commands: package, all, aggregate, verify")
    println(io, "development commands: package-dev, all-dev, aggregate-dev, verify-dev")
    println(io, "other commands: validate, privacy, pdf-privacy [cards-directory], clean")
end

function main(args=ARGS)
    isempty(args) && (usage(stderr); return 2)
    command = args[1]
    if command == "validate"
        length(args) == 1 || error("validate takes no arguments")
        validate_release_sanitization()
        validate_all_matrices()
        return 0
    elseif command == "package"
        length(args) == 2 || error("package requires exactly one package name")
        return generate_package(args[2]) ? 0 : 1
    elseif command == "all"
        length(args) == 1 || error("all takes no arguments")
        release_commit()
        validate_all_matrices()
        passed = true
        for pkg in PACKAGES
            package_passed = try
                generate_package(pkg)
            catch err
                showerror(stderr, err, catch_backtrace())
                println(stderr)
                false
            end
            passed &= package_passed
        end
        aggregate_passed = generate_aggregate()
        return passed && aggregate_passed ? 0 : 1
    elseif command == "package-dev"
        length(args) == 2 || error("package-dev requires exactly one package name")
        return generate_package(args[2]; release=false) ? 0 : 1
    elseif command == "all-dev"
        length(args) == 1 || error("all-dev takes no arguments")
        validate_all_matrices()
        passed = true
        for pkg in PACKAGES
            package_passed = try
                generate_package(pkg; release=false)
            catch err
                showerror(stderr, err, catch_backtrace())
                println(stderr)
                false
            end
            passed &= package_passed
        end
        aggregate_passed = generate_aggregate(; release=false)
        return passed && aggregate_passed ? 0 : 1
    elseif command == "aggregate"
        length(args) == 1 || error("aggregate takes no arguments")
        validate_all_matrices()
        return generate_aggregate() ? 0 : 1
    elseif command == "verify"
        length(args) == 1 || error("verify takes no arguments")
        verify_all_results()
        return 0
    elseif command == "aggregate-dev"
        length(args) == 1 || error("aggregate-dev takes no arguments")
        validate_all_matrices()
        return generate_aggregate(; release=false) ? 0 : 1
    elseif command == "verify-dev"
        length(args) == 1 || error("verify-dev takes no arguments")
        verify_all_results(; release=false)
        return 0
    elseif command == "privacy"
        length(args) == 1 || error("privacy takes no arguments")
        validate_output_privacy()
        return 0
    elseif command == "pdf-privacy"
        length(args) <= 2 || error("pdf-privacy accepts at most one cards directory")
        cards_root = length(args) == 2 ? abspath(args[2]) : CARDS
        validate_rendered_scorecard_privacy(cards_root)
        return 0
    elseif command == "clean"
        length(args) == 1 || error("clean takes no arguments")
        clean_generated()
        return 0
    end
    usage(stderr)
    return 2
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main())
end
